### ISSUE TITLE
Downloadtools method is completely blocking

### ISSUE THREAD

**Issue by mastrolinux** [arduino/arduino-create-agent#105]
Whenever a downloadtools command is triggered the agent waits for the response and if in the meantime there are other activitities running (such as serial monitor) the agents stops reacting and we could see a disconnection in the client side.

For a full example sketch please contact @00alis

**Comment by 00alis** [comment]
I am just uploading this
```
void setup() {
    Serial.begin(9600);
}

void loop() {
    int val = analogRead(A0);
    Serial.print(val);
}
```

On a Zero programming port, alternating with uploading the same sketch on a Uno

**Comment by 00alis** [comment]
this does hasn't happened anymore, @mastrolinux are you sure it is related to downloadtools?

**Comment by mastrolinux** [comment]
yes, if the connection is slow and you do not have the tools installed yet, than the call is completely blocked. You probably have the tools installed now.

**Comment by hannobraun** [comment]
I haven't tried to reproduce, but I don't think this is current anymore. `downloadtool` handling is wrapped in one big goroutine: https://github.com/arduino/arduino-create-agent/blob/b128bca4e66014bed6ce0d55717d2b42540a1df6/hub.go#L169

Can this be closed?

**Comment by umbynos** [comment]
As @hannobraun said, the downloadtool handling is wrapped in a go routine, this
