### ISSUE TITLE
[Win] teal tray icon on blue bar, hard to see

### ISSUE THREAD

**Issue by 00alis** [arduino/arduino-create-agent#107]
From the forum: http://forum.arduino.cc/index.php?topic=361376.msg2803283#msg2803283
Also maybe a slight colour change for the client side toolbar icon as here its like a faint blob on the toolbar.
And no its not a custom toolbar colour either. its windows stock.

![arduino camo](https://cloud.githubusercontent.com/assets/6151328/16144888/22643746-3476-11e6-8787-69474182c234.png)

**Comment by BallscrewBob** [comment]
Just a comment. Almost all the regular Arduino icons have a solid white colour sideways 8 but these have a transparent effect. Maybe reverting to the standard logo ?

**Comment by umbynos** [comment]
Fixed in https://github.com/arduino/arduino-create-agent/pull/575
