### ISSUE TITLE
Check if the directory of a tool exists

### ISSUE THREAD

**Issue by matteosuppo** [arduino/arduino-create-agent#113]
If the user deletes a directory from `~/.arduino-create` the agent doesn't notice and continues thinking it already exists. It should probably check and download the tool again if at startup the folder didn't exist.

**Comment by zmoog** [comment]
The current version of the Agent handle this scenario gracefully: it downloads the tools again both on first start and if the user deletes the directory `.arduino-create` while the Agent is already running.
