### ISSUE TITLE
Incorrect Install Directory on Mac

### ISSUE THREAD

**Issue by dctsystems** [arduino/arduino-create-agent#115]
Installed on Mac, it installs the agent in /Users/username/Applications, rather than ~username/Applications. 

They're the same for accounts created with default settings in Preferences, but for Accounts created in Server App the Home directory can be anywhere - in my case on an external disk with a different name.

It still seems to work, but it _looks like_  the install fails.

**Comment by zmoog** [comment]
Hey @dctsystems, I confirm `/Users/<SYSTEM_USERNAME>/Applications` it's the default installation path. You have the option to customise it during the install.

If you're wondering: yes, it's better later than never.
