### ISSUE TITLE
Installation issue: "destination ${windows_folder_startup} resolved to an empty value"

### ISSUE THREAD

**Issue by smellai** [arduino/arduino-create-agent#118]
http://forum.arduino.cc/index.php?topic=415177.0
http://forum.arduino.cc/index.php?topic=418883.new#new

**Comment by smellai** [comment]
Another one with windows 7
http://forum.arduino.cc/index.php?topic=425344.new#new

**Comment by facchinm** [comment]
see also https://github.com/arduino/Arduino/issues/6010

**Comment by facchinm** [comment]
@anyoneInterested if you could test the development installer and report the result here it would be great. Direct link: http://downloads.arduino.cc/CreateBridge/staging/ArduinoCreateAgent-1.0-windows-installer.exe

**Comment by fonix232** [comment]
I'm having the same issue on Windows 10 Pro (1607). Corporate environment, with main user not having admin rights and using a pseudo-user as SA to install stuff.

This issue happens on both the linked 1.0 development installer, and the 1.1 official.

**Comment by smellai** [comment]
http://forum.arduino.cc/index.php?topic=539489.0

http://forum.arduino.cc/index.php?topic=542465.0

**Comment by zmoog** [comment]
@umbynos I checked on a Windows 10 machine and and I confirm the Agent 1.2 installer requires admin privileges (the app icon has the blue and yellow shield and the User Account Control (UAC) kicks in when you run it).

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/arduino-create-agent/issues/673. Even though this one was submitted much earlier, the other contains more information so I give it preference.
