### ISSUE TITLE
Error Downloading libraries from Arduino online editor

### ISSUE THREAD

**Issue by alieslam** [arduino/arduino-create-agent#131]
As stated in the attached picture, i couldn't manage to download libraries from Arduino's online editor. I have tried to download libraries from "Arduino" and not just "Favorites" but seems working for some libraries and others don't.  

![error while downloading library](https://cloud.githubusercontent.com/assets/8179651/21311740/7ec090b8-c5f1-11e6-8f66-a79ef93bb0d1.png)

**Comment by smellai** [comment]
Hi @alieslam , you are right I'm opening an issue in our create editor repository, if you find any other issue in the editor you can write us here http://forum.arduino.cc/index.php?board=101.0
Thanks!

**Comment by alieslam** [comment]
Hi @smellai ,Thanks for your quick response, I do have another issues so i will be posting them on the forum :).

**Comment by 00alis** [comment]
Thanks a lot!

**Comment by smellai** [comment]
It's a bug with the libraries that have subfolders in the examples. We are going to fix it as soon as possible
