### ISSUE TITLE
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use

### ISSUE THREAD

**Issue by nekhbet** [arduino/arduino-create-agent#133]
On Ubuntu 16, with a fresh install I get: 
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use

Also when running "lsof -i udp:5353" as root: 

COMMAND     PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
avahi-dae   980   avahi   12u  IPv4  19044      0t0  UDP *:mdns 
avahi-dae   980   avahi   13u  IPv6  19045      0t0  UDP *:mdns

**Comment by facchinm** [comment]
Hi @nekhbet ,
that error refers to mdns discovery on ipv6, which is something we don't yet support but it's bundled with the library in use. It should behave as a warning (ie. the agent shouldn't exit). Is it correct?

**Comment by nekhbet** [comment]
You are right, it doesn't exit but also the browser can't connect to it either.

**Comment by facchinm** [comment]
To establish the connection with the browser, a self hosted SSL certificate is needed. We provide it during the installation but we need to refine the procedure **a lot** . If you could, in this order:
- kill the running plugin (via the tray icon or simply with `killall Arduino_Create_Bridge` )
- restart it from the commandline
- paste here the output when you try to open the https://create.arduino.cc/editor website

it would help us a lot in solving the issue, thanks!

**Comment by nekhbet** [comment]
Sorry for the delay, I missed this notification.

So .. I did the first step: "sudo killall Arduino_Create_Bridge")
then re-started it ("sudo /opt/ArduinoCreateAgent-1.1/Arduino_Create_Bridge")


and I got this on the command line: 

```
INFO[0000] map[]                                        
INFO[0000] Version:1.0.46                               
INFO[0000] Hostname: unknown                            
INFO[0000] Garbage collection is on using Standard mode, meaning we just let Golang determine when to garbage collect. 
INFO[0000] You specified a serial port regular expression filter: usb|acm|com
 
INFO[0000] Your serial ports:                           
INFO[0000] 	There are no serial ports to list.          
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET   /                         --> main.homeHandler (2 handlers)
[GIN-debug] GET   /certificate.crt          --> main.certHandler (2 handlers)
[GIN-debug] DELETE /certificate.crt          --> main.deleteCertHandler (2 handlers)
[GIN-debug] POST  /upload                   --> main.uploadHandler (2 handlers)
[GIN-debug] GET   /socket.io/               --> main.(*WsServer).ServeHTTP-fm (2 handlers)
[GIN-debug] POST  /socket.io/               --> main.(*WsServer).ServeHTTP-fm (2 handlers)
[GIN-debug] WS    /socket.io/               --> main.(*WsServer).ServeHTTP-fm (2 handlers)
[GIN-debug] WSS   /socket.io/               --> main.(*WsServer).ServeHTTP-fm (2 handlers)
[GIN-debug] GET   /info                     --> main.infoHandler (2 handlers)
[GIN-debug] POST  /killbrowser              --> main.killBrowserHandler (2 handlers)
[GIN-debug] POST  /pause                    --> main.pauseHandler (2 handlers)
[GIN-debug] POST  /update                   --> main.updateHandler (2 handlers)
[GIN-debug] Listening and serving HTTP on 127.0.0.1:8991
INFO[0000] Inside run of serialhub                      
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use
[GIN-debug] Listening and serving HTTPS on 127.0.0.1:8991
[GIN-debug] [ERROR] listen tcp 127.0.0.1:8991: bind: address already in use
INFO[0000] Error trying to bind to port: listen tcp 127.0.0.1:8991: bind: address already in use, so exiting... 
[GIN-debug] Listening and serving HTTPS on 127.0.0.1:8992

(Arduino_Create_Bridge:804): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: not a number

(Arduino_Create_Bridge:804): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: Expected a string.

(Arduino_Create_Bridge:804): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:832:10: not a number

(Arduino_Create_Bridge:804): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:832:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(Arduino_Create_Bridge:804): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1985:14: not a number

(Arduino_Create_Bridge:804): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1985:14: Expected a string.

(Arduino_Create_Bridge:804): Gtk-WARNING **: Theme parsing error: nautilus.css:55:71: Using one color stop with linear-gradient() is deprecated.

(Arduino_Create_Bridge:804): Gtk-WARNING **: Theme parsing error: nautilus.css:56:71: Using one color stop with linear-gradient() is deprecated.
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use
[ERR] bonjour: Failed to bind to udp6 port: listen udp6 :5353: bind: address already in use
```

on the browser .. it asks me to restart Chrome, I do this but the process itself fails so i manually restart it but the process is again repeated (asking me again to restart for the install to complete).

Thanks.

**Comment by nekhbet** [comment]
Also .. accessing 127.0.0.1:8991 works on HTTP but on HTTPS: 

```
This site can’t provide a secure connection

127.0.0.1 sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

**Comment by nekhbet** [comment]
Ha .. what seems to have solved it was this: access from browser: https://127.0.0.1:8992/ and manually accept the self-signed certificate.

**Comment by facchinm** [comment]
HTTPS should be reachable on :8992, and the Create website should use that port. From the logs it seems that the certificates are ok, anyway try to access https://localhost:8992 and check if the certificate is ok

**Comment by facchinm** [comment]
Great, so the problem was something related with the certificates not being installed system-wide. Are you on Ubuntu 16.04 64bit ? So I can check if the installation works on a VM

**Comment by nekhbet** [comment]
yes, that's the OS

```
cat /proc/version
Linux version 4.8.0-34-generic (buildd@lcy01-21) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016
```

**Comment by facchinm** [comment]
@nekhbet we solved the certificate installation with the latest installer, would you mind testing again so I can close the issue? Thanks!

**Comment by nekhbet** [comment]
Works now. Thank you!

However I noticed another bug "Go to Arduino Create" doesn't open the default system browser but Firefox.
![screenshot from 2017-04-02 10-08-13](https://cloud.githubusercontent.com/assets/2778861/24585169/6c28a19c-178c-11e7-852f-c206d8ca709b.png)

**Comment by facchinm** [comment]
We use https://github.com/skratchdot/open-golang/ to open the link with the default browser, but it looks like `xdg-open` and Ubuntu's "default application"  selector are not exactly the same thing. 
I'll take a look at this, in the meantime I'm closing the issue as solved (for the certificate part)
