### ISSUE TITLE
Edge case when multiple PC identities are using the agent

### ISSUE THREAD

**Issue by 00alis** [arduino/arduino-create-agent#134]
- User A downloads the agent and have it running
- User B downloads the agent and have it running
- User A wants to pause or kill the agent 

This is currently not possible because it Agent A keeps running. 
From the UX point of view this is quite mesmerizing because the action you are doing has no feedback and you might want to turn the agent off cause you need to use the ports or whatever.
We need a way to identify the agent with the specific identity, this way we could close it on one user only.

@mastrolinux

**Comment by zmoog** [comment]
It would be really great to support such a use case, but right now we have to focus on other priorities.
