### ISSUE TITLE
[macOS] uninstaller doesn't remove ~/.arduino-create/

### ISSUE THREAD

**Issue by sandeepmistry** [arduino/arduino-create-agent#138]
Myself and @00alis both tried to uninstall the Agent using the uninstaller. Afterwards the `~/.arduino-create/` folder still contained the tools the Agent had previously downloaded. I would expect those to be removed as part of the uninstall.

**Comment by facchinm** [comment]
:+1: will address this issue in the next installer revamp

**Comment by sandeepmistry** [comment]
The latest dev build v1.0.213 fixes this, closing!
