### ISSUE TITLE
[macOS] agent not runnable after self update?

### ISSUE THREAD

**Issue by sandeepmistry** [arduino/arduino-create-agent#141]
After installing the latest dev build (http://downloads.arduino.cc/CreateBridge/staging/ArduinoCreateAgent-1.0-osx-installer.dmg) the agent is not longer runnable after the first install. I'm using macOS Sierra 10.12.3 (16D32).

![screen shot 2017-02-15 at 12 16 35 pm](https://cloud.githubusercontent.com/assets/1163840/22986998/5ca24fe6-f37b-11e6-803e-5ed959870f0c.png)
<img width="532" alt="screen shot 2017-02-15 at 11 59 29 am" src="https://cloud.githubusercontent.com/assets/1163840/22986999/5cb04362-f37b-11e6-8541-416f8294a247.png">

**Comment by facchinm** [comment]
Solved by latest install script update (1.0.214-dev)
