### ISSUE TITLE
Could not understand command

### ISSUE THREAD

**Issue by jmbaron** [arduino/arduino-create-agent#142]
I installed socket.io but when I go to the debug console and use `socket.emit('command', 'list');` I get an error saying that it could not understand the command. I am on macOS Sierra and I installed socket.io using `npm install socket.io`

**Comment by facchinm** [comment]
Hi @jmbaron ,
that command is intended to be used in a new project based on socket.io.
If you only need to debug your code, simply type `list` . 
If you see no output, enable verbose logging with `log on` and then reissue a `list`
