### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/arduino-create-agent#145]
In the open CREATE page is it possible to have an option in preferences for the sort order of the sketchbook.
Would like to lock it in alpha sort rather than seemingly random between last used and alpha.

Know this page is for AGENT but don't have access to the private repo so if you could maybe copy it over there please.

**Comment by smellai** [comment]
Closing as we already had this issue in the webide repo https://github.com/arduino/webide/issues/1691
