### ISSUE TITLE
PROD and DEV down ?

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/arduino-create-agent#146]
Not 100% sure but both DEV and PROD seem to be stuck at loading source if anyone is watching

Kill this or close if I am mistaken.

**Comment by sandeepmistry** [comment]
I'm seeing this as well, the font service used appears to be down:

https://fonts.typotheque.com/WF-028075-009391.css

**Comment by BallscrewBob** [comment]
Mastro says a t3 on amazon is down but it looks back up again...in Canada.

**Comment by sandeepmistry** [comment]
Closing this for now, things are back up for me.
