### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by arthursw** [arduino/arduino-create-agent#151]
I have the following error when I try to connect my webpage (from chrome) to *arduino-create-agent* through websockets:
 
```WebSocket connection to 'ws://localhost:8991/' failed: Error during WebSocket handshake: Unexpected response code: 200```

Here is the code that I use: 

```typescript
let socket = new WebSocket('ws://localhost:8991/');
```

**Comment by matteosuppo** [comment]
The agent uses socket.io (https://socket.io/docs/) so you'll probably need to open the websocket to wss://localhost:8992/socket.io/ or just use socket.io

**Comment by arthursw** [comment]
Yes, it works with `socketio`. I don't understand why it does with native WebSockets but it works.

**Comment by viettranme** [comment]
For working with native WebSockets, try adding _/websocket_ to the end of your websocket's URL, for example, like: 

`ws://localhost:8991/websocket`
