### ISSUE TITLE
Command placeholders

### ISSUE THREAD

**Issue by matteosuppo** [arduino/arduino-create-agent#158]
Now we only replace the port: https://github.com/arduino/arduino-create-agent/blob/devel/upload/upload.go#L78

But for more complex commands it could be useful a more flexible system.

Maybe instead of a command+signature we could send an encrypted json like

```json
{
"command": "do stuff with $port and $fqbn",
"env": ["port", "env"]
}
```

Along with a non-encrypted json containing the actual value to be replaced:

```json
{
 "commandline": "7bfe45p43lk....",
 "env": {
 "port": "COM4",
 "fqbn": "arduino:avr:uno"
 }
}

What do you think? Are there security issues that I don't see?

**Comment by zmoog** [comment]
Why do we need to change the current command + signature mechanism with something different?
