### ISSUE TITLE
Help with arduino-create-agent, websockets and more

### ISSUE THREAD

**Issue by TharunSonti** [arduino/arduino-create-agent#159]
Hi! 

I'd really appreciate some help with the arduino create agent. I'm having trouble understanding how to use websockets to talk to the arduino create agent. Especially when the other end is not on the same computer that arduino create agent is on but instead somewhere out there on the internet?  

An example or step by step instructions for the create agent would be really helpful? So I could run this on a cloud9 server which I'm using for testing. Or on AWS. I'm running the arduino create agent on a windows computer. I don't have much experience with web stuff beyond basic html or css. More of a firmware and electrical guy. So I'm a bit confused here..

I want to run a website on a cloud9 or aws server (my webpage url right now is of the format: https://ide50-username.cs50.io) and when I access this webpage from my browser (on a computer running arduino create agent in the background) I'd like to be able to interface with create agent and thus the arduinos connected to the computer and send/receive stuff over serial and the internet. 

Examples for websockets keep using "localhost" in the url e.g. "ws://localhost:8989/ws" on chilli pepper or "https://localhost:8991" with the create agent's serial port example webpage that pops up when we click "Open debug console".. Which makes sense to me if the client/server were running on the 1 computer but I don't understand what happens when they're running on 2 different computers.. For each computer does the term "localhost" just refer to itself..? I guess part of what I'm confused about is how does the webpage find out the URL of the person connecting to it and thus of the create agent?

Where does the browser fit into all this? So arduino create agent is on my computer listening on a certain port. I use the browser to access a certain port of a webpage/web server and the browser used one my ports? Can a web server/web page talk back to me once it knows my ip address on any other port I may be listening on? Like the one the arduino create agent is on? I wasn't sure if a web server can access any port of an ip address that connects to it? 

Where does the arduino create agent config file fit into all this? By modifying the config file can the create agent talk straight to my webpage bypassing the browser altogether? 

I noticed that when I opened the "debug console" for the create agent that it took me to localhost:8991 to which the "Serial port example" webpage was served? And I looked at the source code for this web page. Can this source code be run on e.g. a cloud 9 or aws server without modification? I tried this but it didn't seem to connect and print out anything on the webpage unlike when I ran the debug console on my computer and the serial page example webpage would print out empty lists when no arduinos were connected or an arduino's details when they were connected to the computer.. 

Thanks for your time/help! Really appreciate it :)

**Comment by zmoog** [comment]
Hey @TharunSonti are you still interesting on this topic?
