### ISSUE TITLE
Compiling?

### ISSUE THREAD

**Issue by rakeshpai** [arduino/arduino-create-agent#162]
I couldn't find a way to compile sketches locally. Is this possible? If not, could you consider this as an enhancement?

Background: I'm working on [a web-based open-source tool for DIY home automation](https://rakeshpai.github.io/mysensors-network-manager/) based on the Arduino, and am evaluating create-agent for communicating with the hardware. However, since it doesn't appear to do compilation, I'd have to host my own cloud-based compilation service. If create-agent also did compilation, it would make things a lot better. Users would get a trusted compiler toolchain, no one (not even Arduino) needs to host cloud compilers or deal with the associated overheads, and web-based apps (including Arduino Create) get offline support for free. Also, it lowers the barriers for tools like the one I'm working on, allowing for interesting new web-apps. It looks like compiling the sketch locally should be an all-round win.

**Comment by facchinm** [comment]
Hi @rakeshpai ,
the Create Agent has been written to work as a standalone tool for a very specific task (bridging the local boards and Create in a browser-agnostic fashion). Thus it will never be able to compile a sketch on its own. Instead, to perform compilation (also on server side) we use [arduino-builder](https://github.com/arduino/arduino-builder), which is written in golang too, and can be easily integrated with the agent if you need such a tool (the joys of open source :smile: ).
