### ISSUE TITLE
Signatures?

### ISSUE THREAD

**Issue by rakeshpai** [arduino/arduino-create-agent#164]
The readme says:

> signature is the signature of the commandline signed with the private key that matches the public key contained in the config.ini of the arduino-create-agent

However, I couldn't a property name for public keys in config.ini. Moreover, it looks like the code is using a hard-coded key for verifying signatures.

How dp we put our own keys in the config.ini?

**Comment by facchinm** [comment]
`signatureKey` is the flag you are looking for. Golang allows specifying a default value for any flag which will be valid until the flag is defined. So, adding your public key ins config.ini will do the trick (more info https://github.com/arduino/arduino-create-agent/issues/149)
