### ISSUE TITLE
Not able to install Plugin.

### ISSUE THREAD

**Issue by WaldemarLehner** [arduino/arduino-create-agent#173]
![image](https://user-images.githubusercontent.com/27686785/29931133-a9d26f72-8e70-11e7-9963-53b3f2607e31.png)
Install Directory is the default one.

**Comment by facchinm** [comment]
Hi @WaldemarLehner ,
this happens because `$windows_folder_startup` is undefined in SOME Windows installations. We are waiting for a fix from the software we use to package the installer, I'll report back as soon as we get this fixed.

**Comment by zmoog** [comment]
@WaldemarLehner got a chance to installer the Agent 1.2.0? It's using the latest version of the installer.
