### ISSUE TITLE
Agent reserving huge virtual memory space (macOS 10.12 High Sierra)

### ISSUE THREAD

**Issue by destegabry** [arduino/arduino-create-agent#184]
I noticed a huge amount of memory is being allocated from the Arduino Create Agent. 
This happens instantly after running or restarting the agent.

Maybe is nothing to get worried about, the real memory usage is really low, but I think it's worth a check.

`htop` screenshot:
![schermata 2017-10-04 alle 14 32 11](https://user-images.githubusercontent.com/4654358/31176346-d8a04538-a912-11e7-9353-8963c41bee35.png)

**Comment by facchinm** [comment]
Hi @destegabry ,
it is a design feature of any Go program (https://golang.org/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory), no need to worry about it :slightly_smiling_face:
