### ISSUE TITLE
Align logo to web version

### ISSUE THREAD

**Issue by smellai** [arduino/arduino-create-agent#186]
![image](https://user-images.githubusercontent.com/1763268/31546566-221d3172-b024-11e7-9ec2-75c5a36dbe4f.png)

![image](https://user-images.githubusercontent.com/1763268/31546580-2e36d616-b024-11e7-9e54-4209876a76db.png)

**Comment by 00alis** [comment]
that would be great!
![global-webapp-blue](https://user-images.githubusercontent.com/6151328/31602146-65ba1b9a-b25c-11e7-95c2-a4a9a952dcd1.png)
SVG available here https://drive.google.com/open?id=0B_6MhyhSmjXeSW9Ydmx0bW02QkE

**Comment by umbynos** [comment]
Fixed in https://github.com/bcmi-labs/arduino-create-agent-installer/commit/72b132853651d9b5fdb328ed1259223fcd7d7891
