### ISSUE TITLE
Command line signature

### ISSUE THREAD

**Issue by DiegoRam** [arduino/arduino-create-agent#188]
I was trying to perform a successful POST request but I'm getting `invalid signature`. It's pretty confusing on the documentation how to sign and create the hash. There is more examples somewhere?

As far i can undertand there is a private default key defined on main.go file. But I I can get the publick key on client side to sign the field?

**Comment by facchinm** [comment]
Hi @DiegoRam ,
the key defined in main.go is the public key we use to check if the commandline has been signed by us.
To modify it (and use your own key) you can simply modify `config.ini` (which lives in teh same directory of the agent executable) and add your own public key there.
Then, from the server, you should sign every command with your own private key (see https://github.com/arduino/arduino-create-agent/issues/149#issuecomment-301824017 for further info)
