### ISSUE TITLE
Uninstaller on Mac didn't remove added root certificates

### ISSUE THREAD

**Issue by mblackshaw** [arduino/arduino-create-agent#192]
Just tried uninstalled Create and it left the "Arduino" root certificates in my keychain. :(

**Comment by facchinm** [comment]
Hi @mblackshaw ,
thanks for reporting. Did you uninstall the agent using the uninstaller or moving the app into Trash a-la-osx ?

**Comment by mblackshaw** [comment]
I used the uninstaller – and then noticed the certificates were still in the keychain afterwards.

**Comment by facchinm** [comment]
Thanks, I'm investigating it today; thank you for reporting!

**Comment by umbynos** [comment]
Just tested with [1.2.0](https://github.com/arduino/arduino-create-agent/releases/tag/1.2.0) on macOS 11.2 and I can confirm that the certificate get correctly removed during uninstall. Fixed in https://github.com/bcmi-labs/arduino-create-agent-installer/pull/2
