### ISSUE TITLE
Terminal stays open after build [Mac]

### ISSUE THREAD

**Issue by Vancer** [arduino/arduino-create-agent#196]
Hello, I've previously had the same issue with windows and the Arduino team helped me solve it.

So basically what's happening is that I've set all log flags to false and went through the documentation on how to switch to release build.

I've used the GIN command to switch to release, but still the terminal pops up after running the agent using the direct 'double click' method and from the terminal. How can I prevent the terminal from opening after running the agent?

**Comment by facchinm** [comment]
Hi @Vancer ,
on mac, a program will be launched without the terminal if it is packaged as a .app (nothing more than a folder with a very strict structure and some metadata files in it).
Once you "package" the app, double clicking it (and not the executable) will hide the spawning terminal.

**Comment by Vancer** [comment]
Thanks!
