### ISSUE TITLE
When accesing the Web Editor i always land back on the main page

### ISSUE THREAD

**Issue by MakerStuff** [arduino/arduino-create-agent#216]
I can get to a point where i can see the redeem (which i previously agreed on), but thats it.  Restarting did not help.
I tested Windows 10; Google Chrome, Microsoft Edge, Mozilla Firefox.

**Comment by BallscrewBob** [comment]
Confirmed and also reported https://forum.arduino.cc/index.php?topic=520589.new#new by multiple users.

**Comment by MakerStuff** [comment]
Seems like the servers are back online today
