### ISSUE TITLE
300 baud in editor problem

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/arduino-create-agent#227]
It seems specific to AVR boards and I can re-produce here.

[
https://forum.arduino.cc/index.php?topic=545088.new#new
](https://forum.arduino.cc/index.php?topic=545088.new#new)

**Comment by facchinm** [comment]
This is common to all UNO/Mega (see  https://github.com/arduino/Arduino/issues/4714 and https://github.com/arduino/Arduino/pull/2119). The 300bps is not reachable due to a bug in the 16u2 firmware. Closing this one and keeping track in #4717
