### ISSUE TITLE
Typo on Devices page

### ISSUE THREAD

**Issue by piguyisme** [arduino/arduino-create-agent#268]
When it lists what devices can be used on [https://create.arduino.cc/devices/](https://create.arduino.cc/devices/) it says 

> Cloud-enabled products include: UP2 Board, Rasperry Pi, BeagleBone, Intel-based Platforms and Arm-based **Paltforms.**

I'm pretty sure it's supposed to say platforms. This isn't really a bug, so I'm sorry if this shouldn't go here, but I don't know where else to put it.

**Comment by AlbyIanna** [comment]
Thank you for reporting this. I corrected it in the device manager application and the fix should visible soon.
