### ISSUE TITLE
HTTP /info error on Firefox

### ISSUE THREAD

**Issue by mxmarchal** [arduino/arduino-create-agent#269]
Hi,
I worked on a website (HTTPS) and I have a problem with firefox. I followed [https://github.com/arduino/arduino-create-agent/issues/239](url) this because of wss problem with UX but even by doing that, I can't access to HTTP /info and then go to HTTP Endpoint. 

When I tried to check http://127.0.0.1:8991/info, I got a Mixed content blocking error.

I compiled a binary ARM for Raspberry Pi 3 and this is the only one that have this problem. I tried with MacOS and Windows versions, no problem. But with Linux distribs, I can't have it.

I think I'm doing something wrong, but can't figure it out.

Thanks for any future help :) !
Maxence.

**Comment by smellai** [comment]
Hi @Shoodown ,
are you using the last version of Firefox?
It could be very interesting for us to know more about your use case and what you're tring to build with our plugin, if you want to share

**Comment by umbynos** [comment]
Hi, did you succeed in solving the issue?

**Comment by mxmarchal** [comment]
Hi,

It was a long time ago but from what I remember, I started to work on a solution in the source code before giving up because of my lack of knowledge in Go.

So I end up going through another more "homemade" solution using NodeJS inspired by a project I saw on Github but I'm not sure about the name.

I don't have a backup for this project anymore unfortunately.

**Comment by umbynos** [comment]
Ok, nice! From my understanding since the ESR problem was solved, we can close this issue. Feel free to reopen it ☺️
