### ISSUE TITLE
Mega board not recognised on Windows IDE

### ISSUE THREAD

**Issue by hbisby** [arduino/arduino-create-agent#28]
When plugging in the Mega to Windows and using the Create IDE (on Chrome), Mega shows up as "Board at COM5" rather than the expected "Arduino/Genuino Mega 2560 at COM5". When I have tried to select the Arduino Mega as the board for the port before uploading, it still shows the "Board at COM5" in the dropdown list of connected boards as well as the Mega which is shown as disconnected. It is therefore not possible to upload a sketch to the board since the Mega is disconnected and the Board at COM5 does not know which board it is. (However it works without this problem on my Mac.)

**Comment by 00alis** [comment]
Same thing with the Genuino UNO

**Comment by agdl** [comment]
+1 with Zero (Native USB port)
