### ISSUE TITLE
Binary data support

### ISSUE THREAD

**Issue by mbriden** [arduino/arduino-create-agent#29]
Currently all the messages being sent are being explici cast to string (serialport.go, line 113).
Having support for sending binary data through the serial port would be great.

Maybe you could choose a protocol/type of data you want to receive when you open the port?

This would be crucial for the Eslov-system that is going to be ported/implemented into agent/create in the future.

**Comment by facchinm** [comment]
`Timedraw` seial method was merged some times ago, so closing the issue as solved
