### ISSUE TITLE
How to generate binaries for this project?

### ISSUE THREAD

**Issue by arslan77** [arduino/arduino-create-agent#309]
I want to create executable from this project after customizing it for our need of this agent, but when I build it and run the executable nothing happens. No service start in backend.

I shall be very thankful if you can point out the problem and how can I get it done.

**Comment by arslan77** [comment]
Any help/comment will be appreciable.

**Comment by facchinm** [comment]
Launching the executable via commandline should give you enough information on what is going on (or crashing)

**Comment by arslan77** [comment]
Thanks for the reply, I got it. :-)
