### ISSUE TITLE
can't find github.com/sanderhahn/gozip/patchzip

### ISSUE THREAD

**Issue by elopio** [arduino/arduino-create-agent#38]
One of the dependencies is github.com/sanderhahn/gozip/patchzip:
https://github.com/arduino/arduino-create-agent/blob/master/Godeps/Godeps.json#L72

I can't seem to find this project. I can only find gozip: https://github.com/sanderhahn/gozip/

**Comment by facchinm** [comment]
Hi @elopio ,
Godeps has not been updated for some time, regenerating right now!

**Comment by facchinm** [comment]
Fixed by aa13744156e8c05acba49227ebd07c6869ca8fe6

**Comment by elopio** [comment]
thank you!
