### ISSUE TITLE
Consider adding "Configure Origins" to the UI

### ISSUE THREAD

**Issue by joachimhs** [arduino/arduino-create-agent#380]

**Comment by joachimhs** [comment]
In order for third-party developers to use the Arduino-Create-Agent for their arduino-based websites, the end-user need to edit the config.ini file and add in the domain. 

This is something most end-users won't be able to easily do, especially if the target is educational and schools. 

It would be very handy if the UI of the Create Agent enabled the end user to easily add in websites that they would like to enable to create agent for. 

<img width="763" alt="Screen Shot 2019-05-20 at 11 44 34" src="https://user-images.githubusercontent.com/453373/58012417-af1c7f00-7af4-11e9-9579-2627ca8b2894.png">

**Comment by umbynos** [comment]
Thank you for your suggestion, we will add it to the project backlog when we'll have some bandwidth 😁

**Comment by phptuts** [comment]
@umbynos Would you be open to a pr for this?  If so would you want it to open up a webpage to configure this feature?

**Comment by umbynos** [comment]
Hi @phptuts, I asked this question to our the security team and this is what they told me:
>Including a domain in the list of origin that can communicate with the arduino agent implies a high level of trust of the domain. Since we cannot ensure that in this specific case, ElectroBlocks is currently not a partner or anything alike, we should not include it in the official code.

**Comment by per1234** [comment]
Closing as declined according to [the explanation provided in the other issue](https://github.com/arduino/arduino-create-agent/issues/688#issuecomment-1032525149):

>Having a custom menu item to configure just the origins is definitely not a viable solution as we are creating and exception for a specific configuration that can and should be set in the `config.ini` file.
>
>Also, adding a custom web ui has been determined not to be feasible because of [this answer](https://github.com/arduino/arduino-create-agent/issues/380#issuecomment-1029036963)
