### ISSUE TITLE
ArduinoCreateAgent-1.1/Arduino_Create_Bridge: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by inklu** [arduino/arduino-create-agent#384]
Arduino Create Brigde plugin does not start on Debian 8 x64 after installation.
Installation process passed well. But It reports to console these messages:

home/../ArduinoCreateAgent-1.1/Arduino_Create_Bridge: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory
/home/.../ArduinoCreateAgent-1.1/Arduino_Create_Bridge: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory

**Comment by facchinm** [comment]
Hi @inklu ,
one of the prerequisites of the agent is `libappindicator3`.
This library is usually installed in every distro but probably not in Debian8.
Issuing a `sudo apt-get install libappindicator3-1` should solve the issue.

**Comment by inklu** [comment]
Thanks a lot!
