### ISSUE TITLE
errors running main.go

### ISSUE THREAD

**Issue by elopio** [arduino/arduino-create-agent#39]
When I run main.go I get these errors:

elopio@calchas:~/workspace/go/src/github.com/arduino/arduino-create-agent$ go run ./main.go          
# command-line-arguments
./main.go:56: undefined: h in h.broadcastSys
./main.go:90: undefined: hideFile
./main.go:96: undefined: Unzip
./main.go:125: undefined: restart
./main.go:140: undefined: Updater
./main.go:184: undefined: GetList
./main.go:200: undefined: h in h.run
./main.go:202: undefined: sh in sh.run
./main.go:206: undefined: discoverLoop
./main.go:210: undefined: wsHandler
./main.go:210: too many errors

What am I missing here? I suppose I'm doing something terribly wrong, but not sure what.

**Comment by facchinm** [comment]
All files share the same package (it will be refactored sooner or later) so right now only `go build` is supported, sorry
