### ISSUE TITLE
cannot install dependency github.com/sanderhahn/gozip/patchzip

### ISSUE THREAD

**Issue by xrmx** [arduino/arduino-create-agent#48]
Trying to install dependencies but fails:
```
GOPATH=$(pwd) ./bin/godep get ./...
package github.com/sanderhahn/gozip/patchzip: cannot find package "github.com/sanderhahn/gozip/patchzip" in any of:
	/usr/lib/go/src/github.com/sanderhahn/gozip/patchzip (from $GOROOT)
	/home/rm/src/arduino-create-agent/src/github.com/sanderhahn/gozip/patchzip (from $GOPATH)
godep: exit status 1
```

**Comment by facchinm** [comment]
Hi @xrmx ,
the `master` branch is out of date and will be merged soon with `dev` branch.
In the latter one all the dependencies are ok, so I strongly suggest to use that one as starting point for your hacking! :wink:

**Comment by xrmx** [comment]
@facchinm good to know! :) if you are using git-flow-like branching please write it in the README.md. BTW if the master is broken what about switching the default branch in github to devel? thanks

**Comment by facchinm** [comment]
`devel` is now the default branch, thanks for the tip :wink:
