### ISSUE TITLE
Add kill-programmer API

### ISSUE THREAD

**Issue by facchinm** [arduino/arduino-create-agent#5]
The "Interrupt" button in the web interface should have a dual behaviour:
- kill the java IDE if pressed before compilation end
- kill the programmer if pressed after

We should keep track of the spawned process' pid to kill it in a cross platform fashion. Maybe a library exists to do this?

@smellai @matteosuppo @00alis

**Comment by facchinm** [comment]
this one can be backported? https://github.com/johnlauer/serial-port-json-server/commit/11d8a8a021c022b5de5ea0fc270490b0bab4af4c

**Comment by matteosuppo** [comment]
Probably yes. Next week I'll try it

**Comment by facchinm** [comment]
solved with 6b1248ab03b8fe4e1451d346cba6251b890e043c
