### ISSUE TITLE
Launching / Installing fail https handler fail

### ISSUE THREAD

**Issue by lostsh** [arduino/arduino-create-agent#515]
# Instalation of Arduino Create Agent on Debian 10

Installation of the plugin does not seem to work, however, it can be noted that the process proceeds without apparent problems, and that no error messages are returned, however the plugin does not work.

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/9639

**Comment by umbynos** [comment]
Hi, could you please tell us what steps did you followed? It would be really helpful...
What version are you using? What specific problem did you stumbled upon? 
We use installbuilder to generate the installer.
The installer generates a logfile inside `/tmp/installbuilder_installer_XXXX.log`, could you please include it in the issue?
