### ISSUE TITLE
HiDPI support in the installer

### ISSUE THREAD

**Issue by mastrolinux** [arduino/arduino-create-agent#52]
Bitrock Support says:

 <allowWindowResize> property, which will allow you to manually resize the installer window:
```
<project>
   ...
   <allowWindowResize>1</allowWindowResize>
   ...
</project>

 ```

On Windows, we also support DPI aware installers by enabling <enableHDPISupport>:
````
<project>
   ...
   <enableHDPISupport>1</<enableHDPISupport>
   ...
<project>
```

**Comment by facchinm** [comment]
Properties added in `dev` installer
