### ISSUE TITLE
Wrong link in the Arduino Cloud

### ISSUE THREAD

**Issue by kaiomatico** [arduino/arduino-create-agent#556]
Hi, I wanted to set up my new Arduino Nano 33 IoT on Chrome on Linux (Ubuntu 20.04), so I clicked "Configure a new device" in the Arduino Cloud and then it told me I had to download the arduino-create-agent. I was redirected to the following link, where clearly the file no longer exists: https://downloads.arduino.cc/CreateBridgeStable/ArduinoCreateAgent-1.1-linux-x64-installer-safari.tar.gz

So instead I downloaded the arduino-create-agent from this github readme with this link: https://downloads.arduino.cc/CreateBridgeStable/ArduinoCreateAgent-1.1-linux-x64-installer-chrome.tar.gz

The link should be fixed in the arduino cloud so other Users do not get confused I guess

Thanks and have a nice day :)

**Comment by smellai** [comment]
Hi @kaiomatico this issue should be fixed now, thanks for your report!
