### ISSUE TITLE
Warning during install process certmanager.exe

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/arduino-create-agent#572]
### Describe the bug
crash during install of PROD version

### To Reproduce
Install latest version from flow link

### Expected behavior
No errors

## Environment (please complete the following information):
 - Win 10 x 64 pro 
 - Build 19041
 - Browser  chrome, 
 - Browser Version: Version 87.0.4280.66 (Official Build) (64-bit)
 - Agent Version [e.g. 1.0.0]: 1.1.25-318 de 37

## Additional context
![2020-11-25 at 10-31-23re-open](https://user-images.githubusercontent.com/8212730/100249258-5e1bf100-2f0a-11eb-9927-1022493fa8d4.png)

No other information available.

**Comment by umbynos** [comment]
Please could you try with the latest version? [1.2.0](https://github.com/arduino/arduino-create-agent/releases/tag/1.2.0)
Also please try to uninstall the previously installed version before installing the new one

I tried to replicate your problem, but the installation succeeds.

**Comment by BallscrewBob** [comment]
Avast still warns of the alexa virus.
I know this is an FP event but it removes and prevents it from running.

Win 10 x64 pro.

**Comment by zmoog** [comment]
@BallscrewBob is the warning on the installer or the Agent itself?

**Comment by BallscrewBob** [comment]
![image](https://user-images.githubusercontent.com/8212730/105505146-9a639780-5c96-11eb-8f4f-f6c093996bc3.png)
 The installer gives an alexa virus warning but if I try to run the PROD installer I get the one above for a generic virus.

**Comment by BallscrewBob** [comment]
You have to make an EXCEPTION for it.
After making an exception I get this.
![image](https://user-images.githubusercontent.com/8212730/105505555-16f67600-5c97-11eb-986e-201a63b3195d.png)

**Comment by BallscrewBob** [comment]
After the above error I also get the following.
Pretty sure it is linked to the AVAST issue

![image](https://user-images.githubusercontent.com/8212730/105508191-19a69a80-5c9a-11eb-804a-fd6bd33ba934.png)

**Comment by BallscrewBob** [comment]
CONFIRMED it was avast by disabling avast and running the installer as administrator.

**Comment by BallscrewBob** [comment]
HEADS UP was using 1.2 for the last few posts above.

**Comment by zmoog** [comment]
After you disabled Avast, were you able to successfully run the installer and the Agent?

**Comment by BallscrewBob** [comment]
I was able to INSTALL the agent but the agent itself kept closing (seems random or during an upload) leaving me with unable to upload and the message telling me to install the agent comes up in the editor.

**Comment by BallscrewBob** [comment]
Version listed is 1.2.0-5C796D2 btw.

**Comment by umbynos** [comment]
Could you please enable the crashreport? https://github.com/arduino/arduino-create-agent/wiki/How-to-use-crashreport-functionality

**Comment by BallscrewBob** [comment]
Can be closed as was traced down to AVAST AV issues.
