### ISSUE TITLE
Staging agent installs the same version of Dev agent

### ISSUE THREAD

**Issue by 00alis** [arduino/arduino-create-agent#59]
Both staging (1.1) and dev (1.0) versions are 1.0.86 d9eca8e

Therefore the web ide does not communicate with the agent. No yellow FE error message is displayed in the web ide, which is weird.
Error message in Console is the same as in https://github.com/arduino/webide/issues/821

The installer of the staging agent is a slightly different version, it still asks me if I want to use HTTPS or not.

sob
@mastrolinux @matteosuppo

**Comment by facchinm** [comment]
Solved by fixing Jenkins rule
