### ISSUE TITLE
List is empty

### ISSUE THREAD

**Issue by dimensi** [arduino/arduino-create-agent#611]
### Describe the bug
Hello, the agent can't see the ports.

### To Reproduce
Start the agent. Open debug console. Print "list". 

### Expected behavior
List with any ports

## Environment (please complete the following information):
 - OS [e.g. Windows]: Mac OS 11.1
 - Browser [e.g. chrome, safari]: Chrome 
 - Browser Version: 88
 - Agent Version [e.g. 1.0.0]: 1.2.0

## Additional context

![image](https://user-images.githubusercontent.com/11390039/106636691-3cd32300-6593-11eb-9077-6fe303a6f0d8.png)

Arduino Ide see the ports 
![image](https://user-images.githubusercontent.com/11390039/106636979-54aaa700-6593-11eb-8b7a-61a7ad0d6fef.png)

Also I've restarted the agent.

**Comment by umbynos** [comment]
Hello! Are you using the M1 mac?

**Comment by dimensi** [comment]
Yep. Mac mini m1

**Comment by umbynos** [comment]
Unfortunately, the agent does not work out of the box with the new Apple architecture as stated in the [wiki](https://github.com/arduino/arduino-create-agent/wiki#apple-silicon-macs-support). We will add support for it hopefully in the near future
