### ISSUE TITLE
provisioning MKR WiFi1010 fails

### ISSUE THREAD

**Issue by pnndra** [arduino/arduino-create-agent#631]
### Describe the bug
on windows 10 pro, version 10.0.18942 build 19042, board connected through a multifunction USB hub repeatedly fails provisioning. apparently this is due to nina firmware upgrade failing because the tool thinks the board is back from bootloader before it really is

### To Reproduce
just try to provision a board whose Nina firmware needs to be updated. 

### Expected behavior
flawless provisioning

## Environment (please complete the following information):
 - OS [e.g. Windows]: windows 10 pro
 - OS version 10.0.18942 build 19042
 - Browser [e.g. chrome, safari]: edge/Chrome
 - Browser Version: 89.0.774.63 (Official Build) (64 bit)
 - Agent Version [e.g. 1.0.0]: 1.2.1-8d3a8cb
 - CPU architecture [e.g. amd64]

## Additional context
[agent-log (1).txt](https://github.com/arduino/arduino-create-agent/files/6295157/agent-log.1.txt)

**Comment by rsora** [comment]
@pnndra Can you please run this command again:

```
C:/Users/dario.IPTRONIX/.arduino-create/arduino/fwupdater/0.1.3/FirmwareUploader.exe -flasher C:/Users/dario.IPTRONIX/.arduino-create/arduino/fwupdater/0.1.3/firmwares/NINA/FirmwareUpdater.mkrwifi1010.ino.bin -firmware C:/Users/dario.IPTRONIX/.arduino-create/arduino/fwupdater/0.1.3/firmwares/NINA/1.4.1/NINA_W102.bin -address arduino.cc:443 -port COM19 -restore_binary C:/Users/DARIO~1.IPT/AppData/Local/Temp/arduino-create-agent674486686/CheckFirmwareVersion.bin -programmer C:/Users/dario.IPTRONIX/.arduino-create/arduino/bossac/1.7.0-arduino3/bossac
```
And tell us what you get?
Please remember to adjust the COM19 port to the one you have your board attached to
