### ISSUE TITLE
Debug console doesn't seem to work anymore

### ISSUE THREAD

**Issue by mbanzi** [arduino/arduino-create-agent#66]
V 1.0.21-3037740 on OSX 
when I select "open debug console" nothing happens. Web console doesn't show any error. if I try lo reload I get "The connection to ws://localhost:8991/socket.io/?EIO=3&transport=websocket&sid=dlJm4u7YjwpEcajp7G-3 was interrupted while the page was loading. socket.io.min.js:2:19359
TypeError: msg.indexOf is not a function
 localhost:8991:19:50"

**Comment by smellai** [comment]
To see the listing of the boards, try sending the 'log on' command
