### ISSUE TITLE
[Mac] white tray icon on dark scheme

### ISSUE THREAD

**Issue by 00alis** [arduino/arduino-create-agent#67]
From the betatesting http://forum.arduino.cc/index.php?topic=363469.0

> The second issue was that I couldn't see that the Agent was running. My system is set to use the Dark menu bar and Dock - the ArduinoCreateAgent.app does not show an icon on the main display with the Dark menu, it does show on the non-active display menu, so I finally figured out that it was running, and the Agent took me to the http:// pages.

**Comment by 00alis** [comment]
Also the grey icon on Mac is really pixelated, here an updated one https://drive.google.com/a/arduino.cc/file/d/0B7BGUDKhgaDgRWo4ZkNPU2kzcW8/view?usp=sharing

**Comment by 00alis** [comment]
https://github.com/arduino/webide/issues/766

**Comment by smellai** [comment]
http://forum.arduino.cc/index.php?topic=421586.new#new

**Comment by 00alis** [comment]
I know this is not a blocking issue but quite a few people are reporting it :)

**Comment by smellai** [comment]
http://forum.arduino.cc/index.php?topic=426804.0

**Comment by 00alis** [comment]
![tray_iconmac-black](https://cloud.githubusercontent.com/assets/6151328/23663680/9d79aa2c-0353-11e7-9d5d-c50408ff5c3f.png)
![tray_iconmac-grey](https://cloud.githubusercontent.com/assets/6151328/23663679/9d770e02-0353-11e7-99b4-f88b7e4e4031.png)
![tray_iconmac-white](https://cloud.githubusercontent.com/assets/6151328/23663681/9d796b8e-0353-11e7-85f7-fb47590aa0c0.png)

Let me know if we need .ico and I will export the PNGs. Thanks!
