### ISSUE TITLE
Arduino Create Agent JS CLIENT how to use[simple_doubt]

### ISSUE THREAD

**Issue by neptotech** [arduino/arduino-create-agent#684]
Welcome,
currently, I want to upload code to Arduino using JavaScript (NodeJS),
I HATE using FIRMATA to upload code,
I want to use the official `Arduino create agent` and `Arduino create agent js client`

https://github.com/arduino/arduino-create-agent-js-client

I just [downloaded](https://create.arduino.cc/getting-started/plugin/download) the arduino create agent,
I run the below in empty directory
```
git clone https://github.com/arduino/arduino-create-agent-js-client.git
```
 I inserted arduino nano(old bootloader) in COM7,
thus I changed(edited) the file **`.\demo\app.jsx` line 189-205** to,
```
handleUpload() {
    const target = {
      board: 'arduino:avr:nano',
      port: 'COM7',
      network: false
    };

    this.setState({ uploadingPort: target.port });
    daemon.boardPortAfterUpload.subscribe(portStatus => {
      if (portStatus.hasChanged) {
        this.setState({ uploadingPort: portStatus.newPort });
      }
    });

    // Upload a compiled sketch.
    daemon.uploadSerial(target, 'serial_mirror', { bin: HEX });
  }
```
then I run
```
npm run dev
```
-----
since the local host runs on `http://localhost:8000/`
I edited the config file
```
C:\Users\USER\AppData\Roaming\ArduinoCreateAgent\config.ini
```
and set 
```origins = http://localhost:8000```

that is 
```
gc = std  # Type of garbage collection. std = Normal garbage collection allowing system to decide (this has been known to cause a stop the world in the middle of a CNC job which can cause lost responses from the CNC controller and thus stalled jobs. use max instead to solve.), off = let memory grow unbounded (you have to send in the gc command manually to garbage collect or you will run out of RAM eventually), max = Force garbage collection on each recv or send on a serial port (this minimizes stop the world events and thus lost serial responses, but increases CPU usage)
hostname = unknown-hostname  # Override the hostname we get from the OS
regex = usb|acm|com  # Regular expression to filter serial port list
v = true  # show debug logging
appName = CreateAgent/Stable
updateUrl = https://downloads.arduino.cc/
origins = http://localhost:8000 #this is where I have setted
#httpProxy = http://your.proxy:port # Proxy server for HTTP requests
crashreport = false # enable crashreport logging
```
------
![Untitled](https://user-images.githubusercontent.com/85818947/146633215-2577c5d2-faab-4326-b9bc-fd5993f680fa.png)

it keep on uploading as shown above :arrow_up: :arrow_heading_up:

please help

**Comment by umbynos** [comment]
Hi @neptotech, could you please provide the output from the debug console please? To open it just right click on the agent icon and then "open debug console"
