### ISSUE TITLE
M1 Support

### ISSUE THREAD

**Issue by HarounAns** [arduino/arduino-create-agent#691]
The readme says that Mac M1s are currently not supported:
![image](https://user-images.githubusercontent.com/20847319/153719699-2b131683-66ad-4bcf-9c44-2cf35b79837c.png)

but its been over a year, can we get Mac M1 support

**Comment by ubidefeo** [comment]
@HarounAns the Agent does work on M1.
We had to find some workarounds for how certificates are handled and stored but it works well.
A native M1 build still has some quirks to work out, but we're looking into it.
At this moment with Rosetta 2 performing so well it is not a priority.
We will update the readme file mentioning that it does work through Rosetta 2

Thank you for pointing this out
