### ISSUE TITLE
The CI should upload a signed zip bundle to S3, for the new update logic

### ISSUE THREAD

**Issue by umbynos** [arduino/arduino-create-agent#736]
Add a CI step to zip the macOS signed bundle and upload it to S3, this bundle will be used by the new update logic and will be compatible with Ventura requirements

**Comment by umbynos** [comment]
AC: once the release is made on the download bucket on s3 there is a signed bundle. The released bundle should include the version number.

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino/arduino-create-agent/pull/756
