### ISSUE TITLE
Cannot uninstall Arduino Create Agent 1.1

### ISSUE THREAD

**Issue by Coder-256** [arduino/arduino-create-agent#806]
### Describe the problem

I have a very old copy of Arduino Create Agent installed in `~/Applications/ArduinoCreateAgent-1.1`. It's a 32-bit Intel binary so I cannot even run the uninstaller, and newer versions no longer come with a compatible uninstaller. Is there a list of files I can manually remove?

### To reproduce

N/A

### Expected behavior

N/A

### Arduino Create Agent version

N/A but I version 1.3.2 doesn't have an uninstaller

### Operating system

macOS

### Operating system version

13.4.1 (c)

### Browser

Chrome

### Browser version

114.0.5735.198

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-create-agent/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by Coder-256** [comment]
Actually for context, I'm trying to uninstall because I keep getting crashes like this every time I log in:

<details>
<summary><code>Arduino_Create_Bridge-2023-07-12-212402.ips</code></summary>
	-------------------------------------
	Translated Report (Full Report Below)
	-------------------------------------
	
	Process:               Arduino_Create_Bridge [881]
	Path:                  /Users/USER/*/ArduinoCreateAgent.app/Contents/MacOS/Arduino_Create_Bridge
	Identifier:            create.arduino.cc
	Version:               0.1 (0.1)
	Code Type:             X86-64 (Translated)
	Parent Process:        launchd [1]
	User ID:               501
	
	Date/Time:             2023-07-12 21:23:55.0632 -0400
	OS Version:            macOS 13.4.1 (22F770820d)
	Report Version:        12
	Anonymous UUID:        52BB50D0-D67A-976B-88FE-73A57085AC44
	
	
	Time Awake Since Boot: 47 seconds
	
	System Integrity Protection: enabled
	
	Crashed Thread:        0  Dispatch queue: com.apple.main-thread
	
	Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
	Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000000f1
	Exception Codes:       0x0000000000000001, 0x00000000000000f1
	
	Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
	Terminating Process:   exc handler [881]
	
	VM Region Info: 0xf1 is not in any region.  Bytes before following region: 140723139690255
	      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
	      UNUSED SPACE AT START
	--->  
	      mapped file              7ffca8c0c000-7ffcb7d40000 [241.2M] r-x/r-x SM=COW  ...t_id=25aa5a7d
	
	Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
	0   <translation info unavailable>	       0x104dcbbe0 ???
	1   <translation info unavailable>	       0x104dcbbd4 ???
	2   Arduino_Create_Bridge         	         0x4040f03 runtime.signalstack + 99
	3   Arduino_Create_Bridge         	         0x4040c54 runtime.minitSignalStack + 132
	4   Arduino_Create_Bridge         	         0x4029660 runtime.minit + 32
	5   Arduino_Create_Bridge         	         0x40300ec runtime.mstart1 + 108
	6   Arduino_Create_Bridge         	         0x4030074 runtime.mstart + 100
	7   Arduino_Create_Bridge         	         0x4053ea9 runtime.rt0_go + 409
	
	Thread 1:: com.apple.rosetta.exceptionserver
	0   runtime                       	    0x7ff7ffd9d694 0x7ff7ffd99000 + 18068
	
	
	Thread 0 crashed with X86 Thread State (64-bit):
	  rax: 0x000000000000000c  rbx: 0x0000000004904540  rcx: 0x0000000208cea818  rdx: 0x0000000000000000
	  rdi: 0x0000000208cea818  rsi: 0x0000000000000000  rbp: 0x0000000208cea830  rsp: 0x0000000208cea800
	   r8: 0x0000000000000001   r9: 0x0000000000000008  r10: 0x0000000000000010  r11: 0x000000c420010020
	  r12: 0x0000000000000001  r13: 0x0000000000000002  r14: 0x0000000000000008  r15: 0x0000000000000400
	  rip: <unavailable>       rfl: 0x0000000000000243
	 tmp0: 0x00000000000000f1 tmp1: 0x00000000000000f1 tmp2: 0x0000000004040f03
	
	
	Binary Images:
	       0x104beb000 -        0x104c86fff dyld (*) <5db85b72-c63a-3182-91e5-5c942ec30e48> /usr/lib/dyld
	    0x7ff7ffd99000 -     0x7ff7ffdc8fff runtime (*) <c4d322c3-30c5-3c52-adb8-2fd12ec92bc0> /usr/libexec/rosetta/runtime
	       0x10000a000 -        0x10005dfff libRosettaRuntime (*) <73cd5d0d-71d4-353e-9740-af3964d9a4ae> /Library/Apple/*/libRosettaRuntime
	         0x4000000 -          0x48befff create.arduino.cc (0.1) <51c00d6a-b529-303f-9e9b-dbfc1b336b7e> /Users/USER/*/ArduinoCreateAgent.app/Contents/MacOS/Arduino_Create_Bridge
	               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
	
	External Modification Summary:
	  Calls made by other processes targeting this process:
	    task_for_pid: 0
	    thread_create: 0
	    thread_set_state: 0
	  Calls made by this process:
	    task_for_pid: 0
	    thread_create: 0
	    thread_set_state: 0
	  Calls made by all processes on this machine:
	    task_for_pid: 0
	    thread_create: 0
	    thread_set_state: 0
	
	VM Region Summary:
	ReadOnly portion of Libraries: Total=410.1M resident=0K(0%) swapped_out_or_unallocated=410.1M(100%)
	Writable regions: Total=722.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=722.3M(100%)
	
	                                VIRTUAL   REGION 
	REGION TYPE                        SIZE    COUNT (non-coalesced) 
	===========                     =======  ======= 
	Activity Tracing                   256K        1 
	Kernel Alloc Once                    8K        1 
	MALLOC                           179.1M       18 
	MALLOC guard page                   96K        4 
	MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
	Rosetta Arena                     4096K        2 
	Rosetta Generic                   1048K      259 
	Rosetta IndirectBranch              96K        2 
	Rosetta JIT                      128.0M        1 
	Rosetta Return Stack                20K        2 
	Rosetta Thread Context              20K        2 
	VM_ALLOCATE                      528.5G       14 
	VM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)
	__DATA                            14.8M      269 
	__DATA_CONST                      13.1M      166 
	__DATA_DIRTY                       632K       96 
	__FONT_DATA                        2352        1 
	__LINKEDIT                       173.3M        8 
	__OBJC_RO                         66.3M        1 
	__OBJC_RW                         2010K        2 
	__TEXT                           236.8M      289 
	dyld private memory                260K        2 
	mapped file                        4.2G     1281 
	shared memory                       32K        2 
	unshared pmap                     2384K        2 
	===========                     =======  ======= 
	TOTAL                            533.9G     2427 
	TOTAL, minus reserved VM space   533.5G     2427 
	
	
	
	-----------
	Full Report
	-----------
	
	{"app_name":"Arduino_Create_Bridge","timestamp":"2023-07-12 21:24:02.00 -0400","app_version":"0.1","slice_uuid":"51c00d6a-b529-303f-9e9b-dbfc1b336b7e","build_version":"0.1","platform":1,"bundleID":"create.arduino.cc","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4.1 (22F770820d)","roots_installed":0,"name":"Arduino_Create_Bridge","incident_id":"DB325139-8482-4870-BCF1-41B82595820F"}
	{
	  "uptime" : 47,
	  "procRole" : "Unspecified",
	  "version" : 2,
	  "userID" : 501,
	  "deployVersion" : 210,
	  "modelCode" : "MacBookPro18,3",
	  "coalitionID" : 846,
	  "osVersion" : {
	    "train" : "macOS 13.4.1",
	    "build" : "22F770820d",
	    "releaseType" : "User"
	  },
	  "captureTime" : "2023-07-12 21:23:55.0632 -0400",
	  "incident" : "DB325139-8482-4870-BCF1-41B82595820F",
	  "pid" : 881,
	  "translated" : true,
	  "cpuType" : "X86-64",
	  "roots_installed" : 0,
	  "bug_type" : "309",
	  "procLaunch" : "2023-07-12 21:23:44.9535 -0400",
	  "procStartAbsTime" : 890694005,
	  "procExitAbsTime" : 1129835053,
	  "procName" : "Arduino_Create_Bridge",
	  "procPath" : "\/Users\/USER\/*\/ArduinoCreateAgent.app\/Contents\/MacOS\/Arduino_Create_Bridge",
	  "bundleInfo" : {"CFBundleShortVersionString":"0.1","CFBundleVersion":"0.1","CFBundleIdentifier":"create.arduino.cc"},
	  "storeInfo" : {"deviceIdentifierForVendor":"AC00954F-CD39-56C5-AE0E-D2E4947E3344","thirdParty":true},
	  "parentProc" : "launchd",
	  "parentPid" : 1,
	  "coalitionName" : "ArduinoCreateAgent",
	  "crashReporterKey" : "52BB50D0-D67A-976B-88FE-73A57085AC44",
	  "throttleTimeout" : 10,
	  "codeSigningID" : "",
	  "codeSigningTeamID" : "",
	  "codeSigningValidationCategory" : 0,
	  "codeSigningTrustLevel" : 0,
	  "sip" : "enabled",
	  "vmRegionInfo" : "0xf1 is not in any region.  Bytes before following region: 140723139690255\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      mapped file              7ffca8c0c000-7ffcb7d40000 [241.2M] r-x\/r-x SM=COW  ...t_id=25aa5a7d",
	  "exception" : {"codes":"0x0000000000000001, 0x00000000000000f1","rawCodes":[1,241],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000000000000f1"},
	  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":881},
	  "vmregioninfo" : "0xf1 is not in any region.  Bytes before following region: 140723139690255\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      mapped file              7ffca8c0c000-7ffcb7d40000 [241.2M] r-x\/r-x SM=COW  ...t_id=25aa5a7d",
	  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
	  "faultingThread" : 0,
	  "threads" : [{"triggered":true,"id":8153,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":8737695792},"r12":{"value":1},"rosetta":{"tmp2":{"value":67374851},"tmp1":{"value":241},"tmp0":{"value":241}},"rbx":{"value":76563776,"symbolLocation":0,"symbol":"runtime.g0"},"r8":{"value":1},"r15":{"value":1024},"r10":{"value":16},"rdx":{"value":0},"rdi":{"value":8737695768},"r9":{"value":8},"r13":{"value":2},"rflags":{"value":579},"rax":{"value":12},"rsp":{"value":8737695744},"r11":{"value":842350526496},"rcx":{"value":8737695768},"r14":{"value":8},"rsi":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":4376542176,"region":"<translation info unavailable>","imageIndex":4},{"imageOffset":4376542164,"region":"<translation info unavailable>","imageIndex":4},{"imageOffset":265987,"symbol":"runtime.signalstack","symbolLocation":99,"imageIndex":3},{"imageOffset":265300,"symbol":"runtime.minitSignalStack","symbolLocation":132,"imageIndex":3},{"imageOffset":169568,"symbol":"runtime.minit","symbolLocation":32,"imageIndex":3},{"imageOffset":196844,"symbol":"runtime.mstart1","symbolLocation":108,"imageIndex":3},{"imageOffset":196724,"symbol":"runtime.mstart","symbolLocation":100,"imageIndex":3},{"imageOffset":343721,"symbol":"runtime.rt0_go","symbolLocation":409,"imageIndex":3}]},{"id":9780,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18068,"imageIndex":1}]}],
	  "usedImages" : [
	  {
	    "source" : "P",
	    "arch" : "x86_64",
	    "base" : 4374573056,
	    "size" : 638976,
	    "uuid" : "5db85b72-c63a-3182-91e5-5c942ec30e48",
	    "path" : "\/usr\/lib\/dyld",
	    "name" : "dyld"
	  },
	  {
	    "source" : "P",
	    "arch" : "arm64",
	    "base" : 140703126097920,
	    "size" : 196608,
	    "uuid" : "c4d322c3-30c5-3c52-adb8-2fd12ec92bc0",
	    "path" : "\/usr\/libexec\/rosetta\/runtime",
	    "name" : "runtime"
	  },
	  {
	    "source" : "P",
	    "arch" : "arm64",
	    "base" : 4295008256,
	    "size" : 344064,
	    "uuid" : "73cd5d0d-71d4-353e-9740-af3964d9a4ae",
	    "path" : "\/Library\/Apple\/*\/libRosettaRuntime",
	    "name" : "libRosettaRuntime"
	  },
	  {
	    "source" : "P",
	    "arch" : "x86_64",
	    "base" : 67108864,
	    "CFBundleShortVersionString" : "0.1",
	    "CFBundleIdentifier" : "create.arduino.cc",
	    "size" : 9170944,
	    "uuid" : "51c00d6a-b529-303f-9e9b-dbfc1b336b7e",
	    "path" : "\/Users\/USER\/*\/ArduinoCreateAgent.app\/Contents\/MacOS\/Arduino_Create_Bridge",
	    "name" : "Arduino_Create_Bridge",
	    "CFBundleVersion" : "0.1"
	  },
	  {
	    "size" : 0,
	    "source" : "A",
	    "base" : 0,
	    "uuid" : "00000000-0000-0000-0000-000000000000"
	  }
	],
	  "sharedCache" : {
	  "base" : 140703584649216,
	  "size" : 21474836480,
	  "uuid" : "a2b4f9fa-3654-3401-a9f8-42889611882d"
	},
	  "vmSummary" : "ReadOnly portion of Libraries: Total=410.1M resident=0K(0%) swapped_out_or_unallocated=410.1M(100%)\nWritable regions: Total=722.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=722.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           179.1M       18 \nMALLOC guard page                   96K        4 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nRosetta Arena                     4096K        2 \nRosetta Generic                   1048K      259 \nRosetta IndirectBranch              96K        2 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nVM_ALLOCATE                      528.5G       14 \nVM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)\n__DATA                            14.8M      269 \n__DATA_CONST                      13.1M      166 \n__DATA_DIRTY                       632K       96 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       173.3M        8 \n__OBJC_RO                         66.3M        1 \n__OBJC_RW                         2010K        2 \n__TEXT                           236.8M      289 \ndyld private memory                260K        2 \nmapped file                        4.2G     1281 \nshared memory                       32K        2 \nunshared pmap                     2384K        2 \n===========                     =======  ======= \nTOTAL                            533.9G     2427 \nTOTAL, minus reserved VM space   533.5G     2427 \n",
	  "legacyInfo" : {
	  "threadTriggered" : {
	    "queue" : "com.apple.main-thread"
	  }
	},
	  "logWritingSignature" : "09264f5c37456386e5e650cd4ecf47ee10425826",
	  "trialInfo" : {
	  "rollouts" : [
	    {
	      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
	      "factorPackIds" : {
	
	      },
	      "deploymentId" : 240000021
	    },
	    {
	      "rolloutId" : "60da5e84ab0ca017dace9abf",
	      "factorPackIds" : {
	
	      },
	      "deploymentId" : 240000008
	    }
	  ],
	  "experiments" : [
	
	  ]
	}
	}
</details>

**Comment by umbynos** [comment]
It should be sufficient to remove `~/Applications/ArduinoCreateAgent-1.1` folder
