### ISSUE TITLE
Implement discovery protocol

### ISSUE THREAD

**Issue by umbynos** [arduino/arduino-create-agent#891]
As followup of https://github.com/arduino/arduino-create-agent/issues/808 (which correctly fixes the issues), we could benefit from leveraging the discovery protocol. See [comment](https://github.com/arduino/arduino-create-agent/issues/808#issuecomment-1690068701)

**Comment by Xayton** [comment]
This can be tested by the IDE team, design team and IOT using the PR build.

To use this specific build version, just replace the executable (in an existing installation of the agent) with the artifact below:
https://github.com/arduino/arduino-create-agent/actions/runs/7875164059
