### ISSUE TITLE
Add functions to manage certificates on macOS

### ISSUE THREAD

**Issue by Xayton** [arduino/arduino-create-agent#925]
See the full description of the activity here: #907 and the corresponding [comments](https://github.com/arduino/arduino-create-agent/issues/907#issuecomment-1999216448).

- [x] Add a function to remove existing certificates (expired or not)
        https://github.com/arduino/arduino-create-agent/pull/933
- [ ] Add a function to check if the certificates are already present and get also when they will expire

**Comment by MatteoPologruto** [comment]
Add a function to remove existing certificates: https://github.com/arduino/arduino-create-agent/pull/933
