### ISSUE TITLE
Rename the "Arduino Create Agent" to "Arduino Cloud Agent" (phase 1)

### ISSUE THREAD

**Issue by Xayton** [arduino/arduino-create-agent#931]
The current name of the Arduino Agent software should be modified to be in line with the name of the Arduino cloud offerings, that is "Arduino Cloud" (instead of Arduino Create).

This change is motivated by two reasons:
- Improve clarity and reduce misunderstandings (users should not get confused by naming differences). Note that most of the Arduino documentation, tutorials, and blogs reference this software as the "Arduino Cloud Agent".
- Promote the new Arduino branding (Cloud instead of Create).

An internal analysis was conducted to find most of the things that need to be changed. This task focuses on the first sub-set of changes that are either more user-visible or easier to perform. For example changes involving user visible strings or files. Other things like names inside the source code, configuration files and other more complex changes (installer) can be postponed.

List of things to change (not definitive yet):
- Change the name of the application executable (or .app folder)
- Change the name of the installer file and inside the InstallBuilder installer (for platforms that use the installer)
- Update the "Debug Console"
- Update the README and other documentation in the repository

**Note**: the rename activities may affect the Agent update process, as it tries to replace itself. This must be considered when updating from a version with the old name to a version with the new name.

**Comment by MatteoPologruto** [comment]
PR on the installer repository: https://github.com/bcmi-labs/arduino-create-agent-installer/pull/28
