### ISSUE TITLE
"Esptool: No such file or directory" error when uploading code to ESP8266 board

### ISSUE THREAD

**Issue by FlynnMarlie** [arduino/arduino-create-agent#980]
### Describe the problem

The latest release (1.6.0) of the Cloud agent causes uploading any sketch to an ESP8266 board to fail:

```text
Used platform   Version Path                                                            
esp8266:esp8266 2.5.0   /home/builder/.arduino15/packages/esp8266/hardware/esp8266/2.5.0

Flashing with command:{runtime.tools.esptool.path}/esptool -vv -cd nodemcu -cb 115200 -cp /dev/cu.usbserial-02856F96 -ca 0x00000 -cf /var/folders/sx/07hx_hp11nz50sf4ljwylj080000gn/T/arduino-create-agent189194775/new_sketch_1722490854405.bin
Start command: fork/exec {runtime.tools.esptool.path}/esptool: no such file or directory
```

<img width="1067" alt="error 1" src="https://github.com/user-attachments/assets/feef7cd2-ff31-4dc1-b2e0-eb9f87b3a1e3">

We navigated to the "esptool" folder in the .arduino-create directory, but found that this folder is empty. After attempting to place the files it was looking for in the directory manually, it seemed as if the files were getting deleted when the agent attempts to flash the attached device. 

We were able flash to the device and upload the new code by first quitting the agent that was running, then installing the previous version of the agent (version 1.5.0) and then running it. It then allowed us to upload the new code successfully. Going back to version 1.5.0 worked as long as the device didn't restart and the browser wasn't refreshed as a restart or browser refresh caused it to download and use version 1.6.0 again and the issue would happen again. 

Here is a screenshot of how the error was displayed in the console:

![image](https://github.com/user-attachments/assets/d2f17194-8e7d-4a67-a9e3-b582990daf59)

### To reproduce

To reproduce the issue, simply create a new sketch in Arduino Create (https://create.arduino.cc/editor). 

Next, connect an ESP8266 board to the computer and attempt to upload any code to it. The error should show then.

### Expected behavior

It is possible to upload to ESP8266 boards from Arduino Cloud.

### Arduino Create Agent version

1.6.0

### Operating system

- macOS
- Linux

### Operating system version

- macOS: All operating system versions seems to be affected
- Ubuntu 22.04

### Browser

Chrome

### Browser version

All browser versions seems to be affected

### Additional context

Uploading code to an ESP8266 board from Arduino Cloud using a Windows computer works fine.

---

Uploading code to non-ESP8266 boards (including ESP32-based boards) works fine even on Linux and macOS machines.

#### Additional reports

- https://forum.arduino.cc/t/esptool-file-not-found-in-ardunio-cloud-website/1287761
- https://forum.arduino.cc/t/upload-to-esp8266-fails-runtime-tools-esptool-path-esptool-no-such-file-or-directory/1288211
- https://forum.arduino.cc/t/problems-uploading-sketches-from-arduino-cloud/1288083

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-create-agent/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by umbynos** [comment]
The problem has been introduced in 1.6.0 (probably in #953):

Running the same `curl` request:
``` bash
curl 'http://127.0.0.1:8991/v2/pkgs/tools/installed' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Content-Type: text/plain;charset=UTF-8' -H 'Origin: https://app.arduino.cc' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'Priority: u=4' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw '{"checksum":"SHA-256:bded1dca953377838b6086a9bcd40a1dc5286ba5f69f2372c22a1d1819baad24","name":"esptool","packager":"esp8266","signature":"852b58871419ce5e5633ecfaa72c0f0fa890ceb51164b362b8133bc0e3e003a21cec48935b8cdc078f4031219cbf17fb7edd9d7c9ca8ed85492911c9ca6353c9aa4691eb91fda99563a6bd49aeca0d9981fb05ec76e45c6024f8a6822862ad1e34ddc652fbbf4fa909887a255d4f087398ec386577efcec523c21203be3d10fc9e9b0f990a7536875a77dc2bc5cbffea7734b62238e31719111b718bacccebffc9be689545540e81d23b81caa66214376f58a0d6a45cf7efc5d3af62ab932b371628162fffe403906f41d5534921e5be081c5ac2ecc9db5caec03a105cc44b00ce19a95ad079843501eb8182e0717ce327867380c0e39d2b48698547fc1d0d66","url":"https://github.com/earlephilhower/esp-quick-toolchain/releases/download/2.5.0-3/x86_64-linux-gnu.esptool-f80ae31.tar.gz","version":"2.5.0-3-20ed2b9"}'
```

with 1.6.0 :arrow_down: 
```
{"name":"fault","id":"8jjT_VHw","message":"Create file /home/umberto/.arduino-create/esp8266/esptool/2.5.0-3-20ed2b9/esptool: open /home/umberto/.arduino-create/esp8266/esptool/2.5.0-3-20ed2b9/esptool: is a directory","temporary":false,"timeout":false,"fault":true}
```

with 1.5.0
```
{"status":"ok"}
```

**Comment by Xayton** [comment]
We discovered this is a regression caused by [some changes in 1.6.0](https://github.com/arduino/arduino-create-agent/commit/887b22bbf9804958b3752002e51f20548892766a) and by a peculiar structure of the `esptool` packages. The package has a root folder "esptool" with the same name of the file contained in it ("esptool").
